name: CI
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm rebuild
    - run: npm run-script gulp
    - run: npm run-script eleventy
